secret_key_base: W1zl9EmlspjWckPL0-fTkhR7isvwoagAY0JXYsfwx5c
port: 7000
name: amberhost

logging:
  severity: info
  colorize: false
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 4
# ssl_key_file:
# ssl_cert_file:
# redis_url: "redis://localhost:6379"
# database_url: postgres://postgres:@localhost:5432/amberhost_test
auto_reload: false

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:

